apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: 020951019497.dkr.ecr.us-east-2.amazonaws.com/ecommerce/payment-service:48
        ports:
        - containerPort: 8084
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://cloud-config:9296"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE_PREFERIPADDRESS
          value: "true"
        - name: SPRING_CLOUD_CONFIG_FAIL_FAST
          value: "false"
        - name: SERVER_PORT
          value: "8084"
        livenessProbe:
          httpGet:
            path: /payment-service/actuator/health
            port: 8084
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /payment-service/actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
