
CREATE TABLE orders (
	order_id SERIAL PRIMARY KEY,
	cart_id INTEGER,
	order_date TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
	order_desc VARCHAR(255),
	order_fee DECIMAL(7, 2),
	created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
	updated_at TIMESTAMP
);

